name: braden-lol

services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    environment:
      HOST: "0.0.0.0"
      PORT: 80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 1s
      timeout: 1s
      retries: 10
      start_period: 0s
    networks:
      - web

  nginx:
    image: nginx:alpine-slim
    stop_signal: SIGKILL
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "$HOST_PORT:80"
    depends_on:
      web:
        condition: service_healthy
    networks:
      - web

networks:
  web:
