name: braden-lol

services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    environment:
      HOST: "0.0.0.0"
      PORT: 80
      PRESENCE_SERVER_URL: "ws://localhost:${HOST_PORT}/presence/"
    networks:
      - web

  presence:
    build:
      context: .
      dockerfile: ./apps/presence/Dockerfile
    environment:
      HOST: "0.0.0.0"
      PORT: 80
    networks:
      - presence

  nginx:
    image: nginx:alpine-slim
    stop_signal: SIGKILL
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "$HOST_PORT:80"
    depends_on:
      web:
        condition: service_started
      presence:
        condition: service_started
    networks:
      - web
      - presence

networks:
  web:
  presence:
